server:
  port: 8080

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  application:
    name: demo

#  h2:
#    console:
#      enabled: true
#      path: /h2-console  # http://localhost:8080/h2-console
#  datasource:
#    platform: mysql
#    url: jdbc:mysql://database-1.cuvwco5jgynh.ap-northeast-2.rds.amazonaws.com:3306/photato?autoReconnect=true # 변경해주세요
#    username: admin
#    password: amin1234
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true # 실행되는 query를 보여줌
    hibernate:
      ddl-auto: update
  sql:
    init:
      continue-on-error: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  mail:
    # Google smtp server 사용
    host: smtp.gmail.com
    port: 587
    username: schang1008 #앱 비밀번호 발급받은 google 계정
    password: fatnqwqzcvgzgebm #발급받은 앱 비밀번호
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

jwt:
  secret:
    key: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
  token-validity-in-seconds: 86400

redis:
  host: local
  port: 6379

session:
  jdbc:
    initialize:
      schema: always

logging.level:
  org.hibernate.SQL: debug

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password : 1234

cloud:
  aws:
    s3:
      bucket: photaiary-bucket
      dir:
    credentials:
      access-key: ENC(y7/1gk0IwMOJ3TePZf4mejH6sStGtq+kFMtM3s3ngXM=)
      secret-key: ENC(YqFEF4RjnOq2Qx/QKuWi7AAZFCB5kVtWAqG2TDwX7I22L14G7xuAQN3tpPOF3vdxHjCnIi1DNxA=)
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false