cloud:
  aws:
    s3:
      bucket: # 버킷 이름
      dir: # S3 디렉토리 이름
    credentials:
      access-key: # AWS IAM AccessKey 적기
      secret-key: # AWS IAM SecretKey 적기
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false